# Generated by Django 6.0 on 2026-08-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_experience_sandbox_be', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxjob',
            name='facility_name',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
