# Generated by Django 6.0 on 2026-08-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_experience_sandbox_be', '0002_sandboxjob_facility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxjob',
            name='server_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
